### ISSUE TITLE
Flatpak build, make it available on Flathub

### ISSUE THREAD

**Issue by mildred** [julianoappelklein/hokus#17]
See documentation: http://docs.flatpak.org/en/latest/electron.html and https://github.com/flathub/flathub/wiki/App-Submission

I'm willing to do do the work required to have it available on Flathub.

**Comment by julianoappelklein** [comment]
This looks very interesting.

I'll read more about Flatpak when I have the time.
I just want to make sure this will not add any overhead to the development process.
I was expecting to first increase the onboarding rate before doing something like this.

Are you using Hokus?

**Comment by mildred** [comment]
No, I'm not using Hokus yet, but I plan to use it to allow non technical people to edit some website.

I'm trying to get Hokus building on flatpak, but I have an error in building `nodegit`, does it ring a bell for you?

```
[nodegit] Running pre-install script
[nodegit] Configuring libssh2.
[nodegit] Running install script
node-pre-gyp
info it worked if it ends with ok
node-pre-gyp
info using node-pre-gyp@0.6.39
node-pre-gyp info using
node@8.11.2 | linux | x64
node-pre-gyp
info check checked for "/run/build/hokus/main/node_modules/nodegit/build/Release/nodegit.node" (not found)
node-pre-gyp
http GET https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.22.2-electron-v2.0-linux-x64.tar.gz
node-pre-gyp
ERR! Tried to download(undefined): https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.22.2-electron-v2.0-linux-x64.tar.gz 
node-pre-gyp
ERR! Pre-built binaries not found for nodegit@0.22.2 and electron@2.0.3 (electron-v2.0 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp
http
getaddrinfo EAI_AGAIN axonodegit.s3.amazonaws.com:443
gyp

info it worked if it ends with
ok
gyp
info using node-gyp@3.6.2
gyp info using node@8.11.2 | linux | x64
gyp
info ok
gyp

info it worked if it ends with
ok
gyp
info using
node-gyp@3.6.2
gyp
info using
node@8.11.2 | linux | x64
gyp
http GET https://atom.io/download/atom-shell/v2.0.3/iojs-v2.0.3.tar.gz
gyp
WARN install got an error, rolling back install
gyp
ERR! configure error

gyp

ERR!
stack Error: getaddrinfo EAI_AGAIN atom.io:443
gyp

ERR!

stack
at Object._errnoException (util.js:992:11)
gyp

ERR!
stack
at errnoException (dns.js:55:15)
gyp
ERR!

stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
gyp
ERR!

System
Linux 4.19.4-300.fc29.x86_64
gyp

ERR!

command
"/app/bin/node" "/app/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/run/build/hokus/main/node_modules/nodegit/build/Release/nodegit.node" "--module_name=nodegit" "--module_path=/run/build/hokus/main/node_modules/nodegit/build/Release"
gyp
ERR!
cwd /run/build/hokus/main/node_modules/nodegit
gyp ERR!
node -v v8.11.2
gyp ERR!
node-gyp -v v3.6.2
gyp ERR!
not ok
node-pre-gyp
ERR! build error
node-pre-gyp
ERR! stack
Error: Failed to execute '/app/bin/node /app/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/run/build/hokus/main/node_modules/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=/run/build/hokus/main/node_modules/nodegit/build/Release' (1)
node-pre-gyp
ERR! stack     at ChildProcess.<anonymous> (/run/build/hokus/main/node_modules/nodegit/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Linux 4.19.4-300.fc29.x86_64
node-pre-gyp ERR! command "/app/bin/node" "/run/build/hokus/main/node_modules/nodegit/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp
ERR! cwd /run/build/hokus/main/node_modules/nodegit
node-pre-gyp ERR!
node -v v8.11.2
node-pre-gyp ERR!
node-pre-gyp -v v0.6.39
node-pre-gyp
ERR! not ok

Failed to execute '/app/bin/node /app/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/run/build/hokus/main/node_modules/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=/run/build/hokus/main/node_modules/nodegit/build/Release' (1)
[nodegit] ERROR - Could not finish install
[nodegit] ERROR - finished with error code: 1
```

(flatpak builds happens network disconnected, so it cannot download precompiled assets and must builds its own)

**Comment by mildred** [comment]
Found a solution here: https://github.com/flathub/io.lbry.lbry-app/issues/5#issuecomment-388166669

I should be able to provide a flatpak manifest file soon

**Comment by mildred** [comment]
See https://github.com/flathub/flathub/compare/master...mildred:io.hokus.Hokus

**Comment by mildred** [comment]
There is no `npm start` command available, I don't know how to start Hokus from the app directory...

**Comment by julianoappelklein** [comment]
Hello @mildred,
Sorry for the late response. I've been very busy in the last few days.

```npm run dev``` should do.

I see you've made some progress.
What can I do to help you?
