### ISSUE TITLE
Fedora AppImage: `Error: libcurl-gnutls.so.4` and  `Error: libcrypto.so.1.0.0`

### ISSUE THREAD

**Issue by timhughes** [julianoappelklein/hokus#31]
Thanks for what looks to be an awesome product. Unfortunately I cannot try it out because the  AppImage doesn't work on fedora 29.

```
hughest@argon [0] $ ./hokus-cms_linux_x86_64.AppImage 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: libcurl-gnutls.so.4: cannot open shared object file: No such file or directory
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/tmp/.mount_hokus-gz2PkM/resources/app.asar/node_modules/nodegit/dist/nodegit.js:12:12)
    at Object.<anonymous> (/tmp/.mount_hokus-gz2PkM/resources/app.asar/node_modules/nodegit/dist/nodegit.js:1145:3)
```

A temporary workaround for `libcurl-gnutls.so.4` is 
```
sudo ln -s /usr/lib64/libcurl.so.4 /usr/lib64/libcurl-gnutls.so.4
```

The we run into another error 
```
hughest@argon [0] $ ./hokus-cms_linux_x86_64.AppImage 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/tmp/.mount_hokus-jmMm0s/resources/app.asar/node_modules/nodegit/dist/nodegit.js:12:12)
    at Object.<anonymous> (/tmp/.mount_hokus-jmMm0s/resources/app.asar/node_modules/nodegit/dist/nodegit.js:1145:3)
```
Openssl 1.0.0 is no longer supported and should be considered a security issue if software depends on it. 
https://www.openssl.org/policies/releasestrat.html

**Comment by julianoappelklein** [comment]
Hello,

Thank you for your detailed report and for your support!

Hokus depends on nodegit lib. Nodegit uses  Openssl and they eventually will update the version of it.
When it happens, I can release a new Hokus version.

**Comment by timhughes** [comment]
Yeah ok. Looks like this issue https://github.com/nodegit/nodegit/issues/1225 
Nothing to do but wait :-)

**Comment by bjmgeek** [comment]
I can confirm that this issue also exists on Debian buster (stable).  I tried both the AppImage and the deb.  In the case of the deb package, I'd say it may be a missing dependency (libssl of any sort is not listed):

```
$ dpkg-deb -I hokus-cms_linux_amd64.deb 
 new Debian package, version 2.0.
 size 48506740 bytes: control archive=165432 bytes.
     383 bytes,    13 lines      control              
 1074798 bytes,  6281 lines      md5sums              
      95 bytes,     4 lines   *  postinst             #!/bin/bash
      78 bytes,     4 lines   *  postrm               #!/bin/bash
 Package: hokus-cms
 Version: 0.5.0-23
 License: unknown
 Vendor: Juliano Appel Klein <julianoaklein@gmail.com>
 Architecture: amd64
 Maintainer: Juliano Appel Klein <julianoaklein@gmail.com>
 Installed-Size: 181517
 Depends: gconf2, gconf-service, libnotify4, libappindicator1, libxtst6, libnss3, libxss1
 Section: default
 Priority: extra
 Homepage: http://./
 Description: 
   A CMS for Hugo.
```

**Comment by bjmgeek** [comment]
```
$ ./hokus-cms_linux_x86_64.AppImage 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/tmp/.mount_hokus-uFcg68/resources/app.asar/node_modules/nodegit/dist/nodegit.js:12:12)
    at Object.<anonymous> (/tmp/.mount_hokus-uFcg68/resources/app.asar/node_modules/nodegit/dist/nodegit.js:1145:3)
```

**Comment by julianoappelklein** [comment]
**Quick update:** This problem - in the next release - will go away because we are dropping NodeGit in favor of IsomorphicGit. I'll let you know when this happen.

**Comment by julianoappelklein** [comment]
@bjmgeek , @timhughes - You should try the new release - 0.6.0. This issue probably was solved. Let me know if it worked for you.
