### ISSUE TITLE
"Module not found" error on "npm test"

### ISSUE THREAD

**Issue by nickdelgrosso** [julianoappelklein/hokus#48]
Hi,

I'm trying to get a development environment going, and for the most part everything seems fine.  I'm running Windows and VSCode and followed the "Building on Windows" section of the Readme file ("npm install && npm run dist-win").  No errors there.  The program launches on "npm start". Afterward, I ran "npm test" and got a few errors and thought it might be good to share them.  I'm new to npm and node, so I probably did something wrong, but below is the output for you to judge:

```
D:\Nick\ProgrammingProjects\hokus>npm test

> hokus-cms@0.5.0 test D:\Nick\ProgrammingProjects\hokus
> mocha

internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module './src-main/hugo/hugo-downloader'
Require stack:
- D:\Nick\ProgrammingProjects\hokus\test.js
- D:\Nick\ProgrammingProjects\hokus\node_modules\mocha\lib\mocha.js
- D:\Nick\ProgrammingProjects\hokus\node_modules\mocha\index.js
- D:\Nick\ProgrammingProjects\hokus\node_modules\mocha\bin\_mocha
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (D:\Nick\ProgrammingProjects\hokus\test.js:4:60)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at D:\Nick\ProgrammingProjects\hokus\node_modules\mocha\lib\mocha.js:231:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (D:\Nick\ProgrammingProjects\hokus\node_modules\mocha\lib\mocha.js:228:14)
    at Mocha.run (D:\Nick\ProgrammingProjects\hokus\node_modules\mocha\lib\mocha.js:536:10)
    at Object.<anonymous> (D:\Nick\ProgrammingProjects\hokus\node_modules\mocha\bin\_mocha:582:18)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\Nick\\ProgrammingProjects\\hokus\\test.js',
    'D:\\Nick\\ProgrammingProjects\\hokus\\node_modules\\mocha\\lib\\mocha.js',
    'D:\\Nick\\ProgrammingProjects\\hokus\\node_modules\\mocha\\index.js',
    'D:\\Nick\\ProgrammingProjects\\hokus\\node_modules\\mocha\\bin\\_mocha'
  ]
}
npm ERR! Test failed.  See above for more details.
```

**Comment by julianoappelklein** [comment]
Hello Nick!

Don't worry about the test. Just skip this part.

You should focus on how to debug the application. The docs describe how to
do it in the Debugging section.

I hope this helps.
Juliano Appel Klein

**Comment by julianoappelklein** [comment]
Since the tests are not really working. I removed them from npm scripts.
Thank you for bringing this up.
