### ISSUE TITLE
Error on publish

### ISSUE THREAD

**Issue by JLKM** [julianoappelklein/hokus#5]
`Start server` on `localhost:1313` works fine from button at the bottom of the Server Management site. But I can't get `Publish` to work properly.

Relevant settings in `config.yml`:
```
baseurl: /
contentDir: content/
publishDir: public/
```

### Resulting error message
```
Unhandled Error
Error: Could not find a default config.
    at SiteService._findFirstMatchOrDefault (C:/Users/Jan/AppData/Local/Programs/hokus-cms/resources/app.asar/build/electron/services/site/site-service.js:77:19)
    at SiteService.buildWorkspaceForPublish (C:/Users/Jan/AppData/Local/Programs/hokus-cms/resources/app.asar/build/electron/services/site/site-service.js:82:34)
    at C:/Users/Jan/AppData/Local/Programs/hokus-cms/resources/app.asar/build/electron/api.js:114:21
    at C:/Users/Jan/AppData/Local/Programs/hokus-cms/resources/app.asar/build/electron/api.js:27:9
    at Object.get (C:/Users/Jan/AppData/Local/Programs/hokus-cms/resources/app.asar/build/electron/configuration-data-provider.js:71:9)
    at getSiteService (C:/Users/Jan/AppData/Local/Programs/hokus-cms/resources/app.asar/build/electron/api.js:23:31)
    at Object.api.publishWorkspace (C:/Users/Jan/AppData/Local/Programs/hokus-cms/resources/app.asar/build/electron/api.js:112:5)
    at handlers.(anonymous function) (C:/Users/Jan/AppData/Local/Programs/hokus-cms/resources/app.asar/build/electron/ipc-main-binder.js:45:25)
    at EventEmitter.<anonymous> (C:/Users/Jan/AppData/Local/Programs/hokus-cms/resources/app.asar/build/electron/ipc-main-binder.js:67:9)
```

Did I miss something?

**Comment by julianoappelklein** [comment]
Lucky for you, I'm already working on it.

There are some misconceptions in the current serve/build approach, which is very limiting.

A user, when you start a server, should be able to select configurations defined by him, like:

- config.toml
- staging.toml
- ...
- production.toml
- "config.toml,production.toml" (using the inheritance Hugo feature)

The same should apply to when you build something.

Besides that, the build process should not be tied to the publishing process. The user should be allowed to have many publishing ways and destinations (like staging and production).

Do you agree with this approach? It's already on its way, by it's never too late to change the course.

**Comment by julianoappelklein** [comment]
Oh, if you want to use the current build, I believe you should change the **site config** to have a build config:

```
"build": [
  {
    "key":"default",
    "env": {},
    "args": [],
  }
], ...
```

In the next release this config scheme will change a lot. And the build configuration will be movedto the workspace config - in the hokus.{toml, yml,yaml,json} at the root of your website -  (where it makes more sense).

**Comment by JLKM** [comment]
Sorry. This setting in config.yml didn't work out:
```
build:
- key: default
  env: {}
  args: []
```
Added the setting in `hokus.yaml`. Same result.

I'm probably not getting, what you mean by "Site config". Perhaps I should just wait for next release to see publish in action.

**Comment by JLKM** [comment]
Your concept of several config-files for different purposes is spot on in my view. That would make Hokus not only a really useful web-editor (which is awesome in it's own right), but also a must-have add-on/dashboard with extra functions targeted at webmasters/webeditors. It even smells like it might become possible to publish (or serve at localhost) from a selected theme without changing config-files. That would be even more awesome.

**Comment by julianoappelklein** [comment]
You are right.

The idea is to make non-tech people consume Hugo templates by just using Hokus interface.
If this works, Hokus will bring Hugo to a new level, unleashing it's power to a greater audience.

Hokus + Hugo = Wordpress Competitor. It's ambitions, I know.

In the very next version will be possible to start a website from a template. It is already implemented and working with many existent templates. The only problem is that the templates are unaware of Hokus (yet), so they don't provide a hokus.{yaml|json|toml|yml} file.

![screenshot](https://user-images.githubusercontent.com/3170711/45977978-6b36b000-c021-11e8-818b-3c7c598cfbbb.png)

Oh, **by site config I mean the configuration located at the /yourusername/Hokus/someconfig.toml**
I call the hokus.yaml the workspace config. These concepts will be more clear in the future when more site sources will be available. A SiteSource can generate many workspaces.

**Comment by JLKM** [comment]
Really nice work with this. But a little push would come in handy.

After having installed v. 0.2.0 and added your suggestions above. Publish button at Site Management appears to work smoothly. So does the publish dialog, and the message "Site succesfully published" shows up at the end.

The only remaing showstopper: I'm not able to find the published files in `"F:\\data\\hokus\\hugosite\\public"` - or anywhere else for that matter... Replacing `"F:\\data\\hokus\\hugosite\\public"` with `null` doesn't bring any change.

So close...

**Site config (config.hugosite.json):**
```
{
  "key": "hugosite",
  "name": "hugosite",
  "source": {
    "type": "Folder",
    "path": "F:\\data\\hokus\\hugosite"
  },
  "serve": [
    {
      "args": [],
      "env": {}
    }
  ],
  "build": [],
  "transform": [],
  "publish": [
    {
      "key": "default",
      "config": {
        "type": "folder",
        "path": "F:\\data\\hokus\\hugosite\\public"
      }
    }
  ]
}
```

**workspace-config (hokus.yaml):**

```
serve:
- key: default
  config: config.yml
build:
- key: default
  config: config.yml
```

**Hugo config.yml in workspace (exerpt):**
```
contentDir: content/
publishDir: public/
```

**Comment by julianoappelklein** [comment]
You can find the files in the default folder:
C:\Users\{your_user}\Hokus\sites\{your_site_key}\publish\{your_publish_key}

You can also find the last build files in:
C:\Users\{your_user}\Hokus\sites\{your_site_key}\build\{your_build_key}

For now, the publish is just a copy of the build.

I've published a new release, fixing a property naming issue. The process was expecting a "dest" instead of a "path".

I recommend you to download the 0.2.1 version, to use the right convention.

Oh, and you can change your config.hugosite.json to this:

```
{
  "key": "hugosite",
  "name": "hugosite",
  "source": {
    "type": "Folder",
    "path": "F:\\data\\hokus\\hugosite"
  },
  "publish": [
    {
      "key": "default",
      "config": {
        "type": "folder",
        "path": "F:\\data\\hokus\\hugosite\\public"
      }
    }
  ]
}
```

The "serve" and "build" now belongs to the hokus.{ext} file, inside the Hugo site folder. The "transform" is not ready yet and may change.

Your "workspace config" additions look fine. Note that you can have more configs now. I haven't fully tested this yet.

And keep in mind that I overwrite the publishDir in the config.yml by setting a flag --destination for the build (hugo.exe --destination {auto-generated-path}).

Now is time to go deeper and think about a real-world Publisher. The FolderPublisher was just the simplest case I could think to get something working fast. Since you are my most active user, please, I ask you directly: where do you publish your sites? Using which transport mechanism?

To give you directions, I'm thinking about working in one of these (but other ideas are welcome):

- AWSS3Publisher
- GitPublisher
- FTPPublisher

Or do you use Netlify? In this case, a new SiteSource (a GitSiteSource) would be necessary, which is more complicated...

Another question: do you intend to use Hokus in production?

**Comment by JLKM** [comment]
Thank you for your (fast) advice. Now both localhost and publish work fine in my setup.

I have only use Hokus for testing so far, but at this I wouldn't hesitate to use Hokus for managing minor Hugo-websites.

I would be a little more reluctant, when it comes to larger sites. This is due to the exposure of posts as flat lists. Handling hundreds (or as in my case: up to 30.000 posts per site) in Hugo calls for more division of the material. F.ex. based on categories and/or (arche)types/forms.

Unfortunately I'm not able to give any advice with regards to AWSS3Publisher, GitPublisher, FTPPublisher or Netlify. I stick to self-hosting on a small Ubuntu server through Nginx, and this works seamless.

**Comment by julianoappelklein** [comment]
Nice! You are welcome.

You are right about large sites, the UI is not ready to handle it well.
But it can be achieved without too much difficulty.

If you want, create new Issues. I'll attend them when I have time to spare.

Your setup is interesting, very straightforward. You are hosting your websites on the same machine you are developing them.
