### ISSUE TITLE
Error when launching hokus-cms

### ISSUE THREAD

**Issue by InvisibleRasta** [julianoappelklein/hokus#57]
I am getting the following error on debian 10
`A JavaScript error occurred in the main process
Uncaught Exception:
Error: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/opt/Hokus CMS/resources/app.asar/node_modules/nodegit/dist/nodegit.js:12:12)
    at Object.<anonymous> (/opt/Hokus CMS/resources/app.asar/node_modules/nodegit/dist/nodegit.js:1145:3)`

**Comment by julianoappelklein** [comment]
This error is being caused by a library that we removed (nodegit).
The problem will probably go away in the next release (very soon!).
In which OS are getting this error?

**Comment by InvisibleRasta** [comment]
i have tried on debian ,archlinux and mxlinux VM's

**Comment by julianoappelklein** [comment]
@InvisibleRasta - could you try to install the new version? v0.6.0.
We are no longer using nodegit, so I believe it should work well now.
Thank you!
