### ISSUE TITLE
Error when installing/launching on Windows 10

### ISSUE THREAD

**Issue by Backspaze** [julianoappelklein/hokus#59]
I'm unsure if this is related to #57.

I'm running Windows 10.

When the installer finishes, does it try to start the application? The install process went so fast that I'm unsure if it crashed or finished but when it was done the error message below popped up, but the app seems to have been installed but when I click on the Start menu entry it gives the same error.
```
A JavaScript error occurred in the main process

Uncaught Exception:
Error: C:\Users\peter/Hokus/ does not exist.
    at Function.watch [as default] (C:\Users\peter\AppData\Local\Programs\hokus-cms\resources\app.asar\node_modules\node-watch\lib\watch.js:440:7)
    at Object.<anonymous> (C:\Users\peter\AppData\Local\Programs\hokus-cms\resources\app.asar\build\electron\configuration-data-provider.js:85:21)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
    at require (internal/modules/cjs/helpers.js:74:18)
```

**Comment by julianoappelklein** [comment]
@Backspaze - Looks like there is a problem to start the application on Windows when the Hokus folder is not present (in your case, C:\Users\peter\Hokus\).

I updated the binary - just a small patch - and now it shopuld work.

Please, download the installer v0.6.0 again and give it another try.

Please let me know if it works for you.

**Comment by Backspaze** [comment]
Yes, it works now, thanks for the quick fix!

**Comment by julianoappelklein** [comment]
I'm glad it worked!
